name: Blog

on:
  push:
    branches:
      - master
  issues:
    types: [opened, closed, edited, milestoned, labeled, unlabeled, reopened, demilestoned]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
        with:
          repository: xiaohao890809/Issue-Blog-With-Github-Action
          ref: main
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.G_T }}
        run: |
          wget https://raw.githubusercontent.com/xiaohao890809/xiaohao890809.github.io/master/.github/workflows/cv.md -O ./src/cv.md
          wget https://raw.githubusercontent.com/xiaohao890809/xiaohao890809.github.io/master/.github/workflows/custom.js -O ./src/.vuepress/custom.js
          npm install vuepress
          npm install
          npm run action
          npm run build
          npm run deploy